interactions:
- request:
    body: !!binary |
      eyJwcm9wZXJ0aWVzIjogeyJhZGRyZXNzUHJlZml4IjogIjE5Mi4xNjguMC8xNiJ9LCAibmFtZSI6
      ICJub25lX2V4aXN0ZW50In0=
    headers:
      Accept: [application/json]
      Accept-Encoding: ['gzip, deflate']
      Connection: [keep-alive]
      Content-Length: ['74']
      Content-Type: [application/json; charset=utf-8]
      User-Agent: [python/3.5.1 requests/2.9.1 msrest/0.3.0 msrest_azure/0.3.0 networkmanagementclient/2016-03-30
          Azure-SDK-For-Python AZURECLI_0.0.32]
      accept-language: [en-US]
    method: PUT
    uri: https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/cli_test1/providers/Microsoft.Network/virtualnetworks/none_existent/subnets/none_existent?api-version=2016-03-30
  response:
    body: {string: '{"error":{"code":"ResourceNotFound","message":"The Resource ''Microsoft.Network/virtualNetworks/none_existent''
        under resource group ''cli_test1'' was not found."}}'}
    headers:
      Cache-Control: [no-cache]
      Content-Length: ['160']
      Content-Type: [application/json; charset=utf-8]
      Date: ['Wed, 18 May 2016 16:57:21 GMT']
      Expires: ['-1']
      Pragma: [no-cache]
      Strict-Transport-Security: [max-age=31536000; includeSubDomains]
      x-ms-failure-cause: [gateway]
    status: {code: 404, message: Not Found}
version: 1
