interactions:
- request:
    body: null
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      CommandName:
      - backup vault create
      Connection:
      - keep-alive
      ParameterSetName:
      - -n -g --location
      User-Agent:
      - AZURECLI/2.71.0 (MSI) azsdk-python-core/1.31.0 Python/3.11.9 (Windows-10-10.0.26100-SP0)
    method: GET
    uri: https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/clitest.rg000001/providers/Microsoft.RecoveryServices/vaults/clitest-vault000002?api-version=2024-04-01
  response:
    body:
      string: '{"error":{"code":"ResourceNotFound","message":"The Resource ''Microsoft.RecoveryServices/vaults/clitest-vault000002''
        under resource group ''clitest.rg000001'' was not found. For more details
        please go to https://aka.ms/ARMResourceNotFoundFix"}}'
    headers:
      cache-control:
      - no-cache
      content-length:
      - '241'
      content-type:
      - application/json; charset=utf-8
      date:
      - Tue, 29 Apr 2025 10:51:25 GMT
      expires:
      - '-1'
      pragma:
      - no-cache
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      x-cache:
      - CONFIG_NOCACHE
      x-content-type-options:
      - nosniff
      x-ms-failure-cause:
      - gateway
      x-msedge-ref:
      - 'Ref A: FD653ACBBA9B49DDAF76C084DC8A5CC9 Ref B: MAA201060515029 Ref C: 2025-04-29T10:51:25Z'
    status:
      code: 404
      message: Not Found
version: 1
